name: CICD

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
env:
  # Postgres
  POSTGRESQL_DB: seidtech
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  # Java
  JAVA_VERSION: 17
  # AWS & Elastic Bean Stalk
  AWS_REGION: us-east-2
  EB_ENVIRONMENT_NAME: Springbootreactfullstack-env-1
  EB_APPLICATION_NAME: springboot-react-fullstack
  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/docker-compose.yml
  BUCKET_NAME : elasticbeanstalk-us-east-2-943395628474
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build Number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%-d.%-m.%Y.%-H.%-M.%-S')" >> $GITHUB_OUTPUT
        #run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"
        
      - name: Save state
        run: echo "DOCKER_HUB_USERNAME=sredi" >> $GITHUB_ENV
        
      - name: Docker Login
        uses: docker/login-action@v2
        #uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORDS }}
      - name: Maven Clean Package and Push to Dockerhub
        run: |
          ./mvnw --no-transfer-progress clean package \
            -P build-frontend \
            -P jib-push-to-dockerhub \
              -Dapp.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}}
              
      - name: Update and commit app version in docker-compose.yaml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          sed -i -E 's_(sredi/springboot-react-fullstack:)([^"]*)_\1'${BUILD_NUMBER}'_' elasticbeanstalk/docker-compose.yml
          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add elasticbeanstalk/docker-compose.yml
          git commit -m "new app version: ${BUILD_NUMBER}"
          git push
          
      - name: Configure AWS creditials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::943395628474:oidc-provider/token.actions.githubusercontent.com
          role-session-name: ElasticBeanstalkDeployment
          aws-region: ${{ env.AWS_REGION }}
          
      # Upload a file to AWS s3
      - name: Upload docker-compose.yml to S3 bucket
        run: |
          aws s3 cp ${{ env.EB_DEPLOYMENT_PACKAGE }} s3://${{ env.BUCKET_NAME }}/
      
      
      
      
      
      
      
      
      
      
